name: GCM

on:
  workflow_dispatch:
  push:
    branches: [ main, linux ]
  pull_request:
    branches: [ main, linux ]

jobs:
  validate_gcm:
    name: "CI"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-latest]

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build Windows
      if: contains(matrix.os, 'windows')
      run: dotnet build --configuration WindowsRelease

    - name: Build Linux
      if: contains(matrix.os, 'ubuntu')
      run: dotnet build --configuration LinuxRelease

    - name: Build macOS
      if: contains(matrix.os, 'macos')
      run: dotnet build --configuration MacRelease

    - name: Test
      run: dotnet test --verbosity normal
